data = {
	Appraiser_Devaluation = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Appraiser_OverEstimate = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	ApproachPad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.044166,
			width = 15.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Archer_Distortion = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Archer_JincanGu = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Archer_SpikeShooter = {
		{
		},
	},
	Archer_VerminPot = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Archer_Zhendu = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Arditi_Taglio = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 45.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 300,
		},
	},
	Arditi_TreGranata = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Assassin_HallucinationSmoke = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 55.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	GM_MGAME_BORUTA_HATE_RESET_PAD = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 3000,
		},
	},
	BK_MGAME_BORUTA_HATE_RESET_PAD = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 3000,
		},
	},
	BK_MGAME_ECHO_PAD = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.7275858,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 5000,
		},
	},
	BK_MGAME_FEVER_PAD = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.5425889,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	BK_MGAME_FEVER_REVERSE = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.83180231,
			width = 250.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 2000,
		},
	},
	BackMasking = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0025850763,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Barbarian_Pouncing = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 45.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 300,
		},
	},
	BebeMagePrist_Safetyzone = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.31544101,
			width = 15.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 300,
		},
	},
	Bokor_BwaKayiman_Fluting = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.044166,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Boss_ProddedHorse = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.1196735,
			width = 300.0,
			length = 20.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Boss_ProddedHorse2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.99962974,
			width = 300.0,
			length = 20.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Boss_ignas_circlewave = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 10.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 300,
		},
	},
	Boss_ignas_circlewave_electShock = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 10.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	Boss_slow = {
		{
			timestart = 0,
			timeend = 0,
			angle = 6.9177952e+22,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 150,
		},
	},
	Bramble_NearAttack = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Bramble_SpDrain = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 200.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	BubeMageFire_FirePillar = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	BubeMageNormal_ReflectShield = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 55.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	BubeMagePrist_Heal = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.079396,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 150,
		},
	},
	CHAPLE576_MQ_08 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.18292604,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	CHAPLE577_MQ_06 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.7639129,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	CallOfDeities = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Cannoneer_SiegeBurst_FlashBomb = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 300.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cannoneer_SmokeGrenade = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 55.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Carapace_Spin = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Centurion_Conscript = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.256834,
			width = 7.5,
			length = 7.5,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Centurion_CoolDown = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.256834,
			width = 7.5,
			length = 7.5,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Centurion_Schiltron_Active = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.044166,
			width = 35.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 50,
		},
	},
	Centurion_Testudo = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 7.5,
			length = 7.5,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Centurion_Winged_Formation = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.000696,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Centurion_Winged_Formation_Debuff = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 0.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Centurion_phalanx_formation = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.256834,
			width = 7.5,
			length = 7.5,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Centurion_schiltron_formation = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.61487001,
			width = 7.5,
			length = 7.5,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Centurion_skirmishers_formation = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.256834,
			width = 7.5,
			length = 7.5,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Centurion_tercio_formation = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.61487001,
			width = 7.5,
			length = 7.5,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Centurion_wedge_formation = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.61487001,
			width = 7.5,
			length = 7.5,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Chaplain_BuildCappella = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 90.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Chaplain_MagnusExorcismus = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Chronomancer_Pass = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.079396,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Chronomancer_Slow = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 27.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Chronomancer_Stop = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.51614898,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Cleric_Barrier = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 0.60000002,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Cleric_Barrier_PC = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 1.2,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Cleric_Conversion = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 35.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_Fade = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cleric_IronSkin = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 0.0,
			length = 0.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Cleric_Laima = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cleric_Mackangdal = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.079396,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Cleric_Melstis = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.51614898,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cleric_Melstis_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 120.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_Monstrance = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cleric_New_Aukuras = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.277462,
			width = 120.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Cleric_New_Bless = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 50,
		},
	},
	Cleric_New_Cure = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 400,
		},
	},
	Cleric_New_Cure_10 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.044166,
			width = 20.0,
			length = 20.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Cleric_New_Cure_5 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.044166,
			width = 15.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Cleric_New_Cure_Abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Cleric_New_Haste = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.56099099,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Cleric_New_Heal = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 400,
		},
	},
	Cleric_New_HolyBaptism = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.136574,
			width = 12.5,
			length = 12.5,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 400,
		},
	},
	Cleric_New_HolyEnchant = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_New_Limitation = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.447628,
			width = 25.0,
			length = 25.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 600,
		},
	},
	Cleric_New_SafetyZone = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Cleric_New_SafetyZone_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Cleric_OgouVeve = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.277462,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_OgouVeve_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 110.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_PatronSaint = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 400,
		},
	},
	Cleric_ResistElements = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.6770639,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cleric_Restoration = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 3000,
		},
	},
	Cleric_RighteousZone = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Cleric_Romuva = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 82.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_Romuva_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 55.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_Samdiveve = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.277462,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_Samdiveve_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 110.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_SummonTorch = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.744998,
			width = 60.0,
			length = 60.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 1000,
		},
	},
	Cleric_Summonghede = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_Zaibas = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 35.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 150,
		},
	},
	Cleric_Zalciai = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 42.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_Zemina = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cleric_Ziva = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.51614898,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Cleric_Zombierize = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 45.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cleric_equalizerMissile = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 70.137886,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cleric_jangpantest = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.426752,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Cleric_testPad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 0.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cleric_testPad2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 0.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Colimencia_circlewave = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 10.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 300,
		},
	},
	Corsair_JollyRoger = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.277462,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Cryomancer_FrostPillar = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 60.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cryomancer_Gust = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Cryomancer_IceWall = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 12.0,
			length = 12.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Cryomancer_SubzeroShield = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.044166,
			width = 10.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 10,
		},
	},
	Daoshi_CreepingDeath = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Daoshi_DarkSight = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Daoshi_PhantomEradication = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 70.0,
			length = 50.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Daoshi_StormCalling = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 800,
		},
	},
	Daoshi_StormCalling_Mine = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Daoshi_TriDisaster = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Dievdirbys_CarveAusirine = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Dragoon_Gae_Bulg_atkabil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 45.0,
			length = 45.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Dragoon_Gae_Bulg_defabil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 45.0,
			length = 45.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Drapeliun_circlewave = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 10.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 300,
		},
	},
	Druid_HengeStone = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Elementalist_FreezingSphere = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Elementalist_FrostCloud = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Elementalist_Hail = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Elementalist_Rain = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Enchanter_Empowering = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Enchanter_EnchantLightning = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Enervation_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Evil_Pillar = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Exorcist_AquaBenedicta = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.8468292,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Exorcist_Entity = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.4284449,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Exorcist_Rubric = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.8994689,
			width = 40.0,
			length = 100.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Exorcist_Rubric_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.8994689,
			width = 40.0,
			length = 100.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 250,
		},
	},
	FTOWER691_moving_1 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.084464796,
			width = 70.0,
			length = 176.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	FTOWER691_moving_2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 4.8617305e+30,
			width = 70.0,
			length = 176.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	F_boss_Prisoncutter_CriticalWound_Zone = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.2875659,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Falconer_Aiming = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Falconer_Circling = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Falconer_Circling_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	FanaticIllusion_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.3444525,
			width = 60.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Featherfoot_BloodBath = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Featherfoot_Kurdaitcha = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	FireClaw_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	FireWall = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 0.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	FlareShot_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Fletcher_MagicArrow = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Friedenslied_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 120.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	GPAD_GT_GTAGE13_0 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.4962163,
			width = 80.0,
			length = 350.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 2000,
		},
	},
	GPAD_GT_GTAGE13_135 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.4962163,
			width = 80.0,
			length = 350.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 2000,
		},
	},
	GPAD_GT_GTAGE13_180 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.4962163,
			width = 80.0,
			length = 350.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 2000,
		},
	},
	GPAD_GT_GTAGE13_225 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.4962163,
			width = 80.0,
			length = 350.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 2000,
		},
	},
	GPAD_GT_GTAGE13_270 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.4962163,
			width = 80.0,
			length = 350.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 2000,
		},
	},
	GPAD_GT_GTAGE13_315 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.4962163,
			width = 80.0,
			length = 350.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 2000,
		},
	},
	GPAD_GT_GTAGE13_45 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.4962163,
			width = 80.0,
			length = 350.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 2000,
		},
	},
	GPAD_GT_GTAGE13_90 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.4962163,
			width = 80.0,
			length = 350.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 2000,
		},
	},
	Genmagnus_circlewave = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 10.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 300,
		},
	},
	GiganteMarcha_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	GravityPole_PVP = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 75.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	GreenwoodShikigami_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 600,
		},
	},
	GreenwoodShikigami_Pad_Effect = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Grinender_FirePillar = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 13.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Guild_Colony_Invinciblation = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.7225536,
			width = 300.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Hackapell_BombardmentOrders = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	HeavyGravity_PAD = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 120.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Hepatica_King_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 35.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Highlander_CrossGuard = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.079396,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	ID_WHITETREES1_GIMMICK2_PAD = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.4823527,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	ID_kucarry_blazermancer_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	INVINCIBILITY_BREAK = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	IceWall_Force = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Inquisitor_BreakingWheel = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.4871173,
			width = 45.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Inquisitor_FireWall = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Inquisitor_LeadSprinkler = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Inquisitor_MalleusMaleficarum = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Invocation_DARKATK_Abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Ironbaum_fire2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 60.0,
			length = 18.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Kabbalist_Merkabah = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 35.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Kerberos_FireStadium = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.8843095,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Lapene_Donuts = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.7168163,
			width = 35.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	Lapene_Donuts1 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.7168163,
			width = 60.0,
			length = 40.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	Lapene_Donuts2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.7168163,
			width = 80.0,
			length = 50.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	Lapene_Donuts3 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.7168163,
			width = 125.0,
			length = 95.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	Lithorex_bubble = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Malletwyvern_hammer = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 35.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Matador_CorridaFinale = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.4082489,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Matador_CorridaFinale_Abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.551312,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Matross_CanisterShot = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 120.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Matross_CanisterShot_End = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 120.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Mergen_ArrowRain = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Mergen_ArrowRain2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Mergen_DownFall = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Miko_Hamaya = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Miko_Hamaya_TakeDamage = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 50,
		},
	},
	Miko_HoukiBroom = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 45.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Miko_KaguraDance = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 130.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mirtis_Cloud = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.7438819,
			width = 60.0,
			length = 60.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Mirtis_line = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 200.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Mirtis_line_small = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 80.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Mirtis_line_time = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0025850763,
			width = 200.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	Moldyhorn_spd_down = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.43075699,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Moldyhorn_spd_down_pc = {
		{
			timestart = 0,
			timeend = 0,
			angle = 4.6174734e+24,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Moldyhorn_takedamage = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.74359298,
			width = 57.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Moldyhorn_takedamage2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.92519403,
			width = 150.0,
			length = 70.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	Mon_Elite_Buff = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mon_Elite_Debuff = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mon_Elite_Holding = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mon_FirePilla = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 20.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Mon_FirePilla_5 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.130331,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Mon_Fireball_santan = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mon_Heal = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Mon_PoisonPilla = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.0598876,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mon_PoisonPilla_orange = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mon_PoleofAgony = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.8928199,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Mon_ReflectShiedl = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mon_StarTower_Vesperia = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.922819,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mon_StarTower_punter = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mon_Tala_Ground = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.8928199,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Mon_Zaibas = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Mon_bloom_Lighting = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.8928199,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Mon_cure = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Mon_firewall = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.1305707e+24,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 300,
		},
	},
	Mon_movetrap = {
		{
			timestart = 0,
			timeend = 0,
			angle = 6.9177952e+22,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Monk_Golden_Bell_Shield_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 35.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Monster_FireBall = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Monster_Haste = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.744249e+28,
			width = 10.0,
			length = 10.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	Monster_Poison = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.9419019,
			width = 27.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Monster_Sleep = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 35.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 600,
		},
	},
	Monster_Slow = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 33.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Nachash_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 60.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 2000,
		},
	},
	Necromancer_CreateShoggoth_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Necromancer_DirtyWall = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Necromancer_FleshHoop_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Necromancer_FleshStrike = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Nepenthes = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Nuodai_Poison_Remove = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0025850763,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Oracle_DivineMight = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Oracle_DivineMight_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Oracle_Foretell = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Oracle_Foretell_Magic = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Oracle_Foretell_Missile = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Oracle_Foretell_TrueDamage = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Oracle_Prophecy = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Paladin_Sanctuary_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	PiedPiper_Fluting = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.044166,
			width = 120.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	PlagueDoctor_Bloodletting = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	PlagueDoctor_Disenchant = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 50,
		},
	},
	PlagueDoctor_Fumigate_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	PlagueDoctor_HealingFactor = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 400,
		},
	},
	PlagueDoctor_Incineration = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 35.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 50,
		},
	},
	PlagueDoctor_PlagueVapours = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Priest_Dodola = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.079396,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Priest_Exorcise = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 400,
		},
	},
	PsychicPressure_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 25.0,
			length = 25.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Psychokino_Raise = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Pyroego_FirePillar = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.1394898,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Pyromancer_FireWall = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	Pyromancer_FlameGround = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Pyromancer_HellBreath = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 800,
		},
	},
	QuarrelShooter_DeployPavise = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Rajatoad_bubble = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Rancer_Charge = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	RingCrawler_ElectricFields = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.5647116,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Rodelero_ShieldCharge = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.75697756,
			width = 10.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 400,
		},
	},
	Rogue_Lachrymator_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 75.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Rogue_Vendetta = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	RuneCaster_Algiz = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 10,
		},
	},
	RuneCaster_Isa = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	RuneCaster_Stan = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	RuneCaster_Thurisaz = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 400,
		},
	},
	Sadhu_Bind = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.079396,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Sadhu_Prakriti = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Sadhu_Suppress = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.51614898,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Sadhu_TransmitPrana = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.079396,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 300,
		},
	},
	Sage_HoleOfDarkness = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Sage_HoleOfDarkness_End = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Sage_HoleOfDarkness_Start = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Sage_Maze = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 800,
		},
	},
	Sage_MicroDimension = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Sage_UltimateDimension = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Sapper_LegHoldTrap = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Sapper_SpringTrap = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Sapper_StakeStockades = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Scan_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	ShadowGaoler_circlewave = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 10.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 300,
		},
	},
	Sheriff_Fanning = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 65,
		},
	},
	Shootpad_Fireball = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Shootpad_RapidFire = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Skiaclipse_pad_1 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.28712228,
			width = 45.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Skiaclipse_pad_2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.8100181,
			width = 35.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Skiaclipse_pad_3 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 60.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Skiaclipse_pad_4 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 60.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Skiaclipse_pad_5 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -3.0146148,
			width = 60.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Skiaclipse_pad_6 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Skiaclipse_pad_7 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 60.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Sparnas_skill_5 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.051339,
			width = 32.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Square_Unknocker = {
		{
			timestart = 0,
			timeend = 0,
			angle = 3.039305,
			width = 10.0,
			length = 50.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	StormDust_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 75.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	SubWeapon_SnowSpray = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.0511272,
			width = 25.0,
			length = 15.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 250,
		},
	},
	Summon_DefDown = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.6480041e-10,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Summon_Lethargy = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.6480041e-10,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Summon_Magnet = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.6480041e-10,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Summon_Silence = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.6480041e-10,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Templer_AdvancedOrders = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Templer_BattleOrders = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Templer_BuildShieldCharger = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.539212,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	Templer_FlyingColors = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Templer_NonInvasiveArea = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Templer_NonInvasiveArea_HorseRiding = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Templer_ReduceCraftTime = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.277462,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Templer_ShareBuff = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Templer_ShareBuff_Abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 160.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Tetmamakla_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Thaumaturge_Quicken = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.277462,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Thaumaturge_Reversi = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Thaumaturge_Reversi_abil = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Thaumaturge_ShrinkBody = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.079396,
			width = 50.0,
			length = 40.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Thaumaturge_SwellBody = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.079396,
			width = 50.0,
			length = 40.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	Thaumaturge_SwellBrain = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	TheTreeOfSepiroth_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	TombMaiden_circlewave = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 10.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 300,
		},
	},
	TombMaiden_line = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	TombMaiden_line2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Toyou_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Velo_Holdbuff = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.544415,
			width = 77.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Warlock_Mastema = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 60.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	Warlock_PoleofAgony = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.75,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Warlock_Sabbath_Fluting = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.044166,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	Warrior_GreatBear = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.079396,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Wizard_Darkness = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Wizard_Fog = {
		{
			timestart = 0,
			timeend = 0,
			angle = 3.058759,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Wizard_Lethargy = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 37.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Wizard_New_EnchantFire = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.47773829,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Wizard_New_FirePillar = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.7451191,
			width = 27.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Wizard_New_FirePillar10 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Wizard_New_FirePillar100 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.67606294,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	Wizard_New_FirePillar5 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 22.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	Wizard_Sleep = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 37.5,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Wizard_reflect = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.554453,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 600,
		},
	},
	Yekub_skill_2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 23.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	YinYangConsonance_Pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 120.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	Zaura_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.55317026,
			width = 200.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	boss_Kerberos_Reversi = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	boss_Neop_PoisonFillar = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.2482388,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	boss_Raid_Gimmick = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.3819699,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	boss_RingCrawler_Rize = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 60.0,
			length = 60.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	boss_Simorfh = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.04711502,
			width = 60.0,
			length = 35.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	boss_Simorfh2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 95.0,
			length = 65.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	boss_Simorph3 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 135.0,
			length = 100.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	boss_asiomage_doughnut = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.87338102,
			width = 150.0,
			length = 80.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	boss_asiomage_fire = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.7854113,
			width = 50.0,
			length = 20.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	boss_asiomage_square = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.7782132,
			width = 40.0,
			length = 100.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	boss_blackGargoyle = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.97081614,
			width = 30.0,
			length = 100.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 250,
		},
	},
	boss_firewall = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.0,
			width = 20.0,
			length = 20.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	boss_firewall_highlevel = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.2164313,
			width = 20.0,
			length = 20.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	boss_firewall_red = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.1416562e-10,
			width = 20.0,
			length = 20.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	boss_froster_lord = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.0844191,
			width = 45.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	boss_hydra_square = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 100.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 250,
		},
	},
	boss_jezebel_force = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.2853494,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 250,
		},
	},
	boss_lucy_summoner_zone = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	boss_madara_Circle = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.6377366,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	boss_nuodai_hail = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 60.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	boss_pnatorex_missile = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.74521101,
			width = 20.0,
			length = 40.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 250,
		},
	},
	boss_square = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 220.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	boss_uniq_ignas = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.1355958,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	boss_uniq_ignas_circlewave = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 10.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	boss_uniq_ignas_cloud = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	boss_velcoffer_Reversi = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	boss_warpulis_windpad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.65906525,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	boss_woodhoungan = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	counterspell_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 1000,
		},
	},
	cover_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 3.0275183,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	cyclone_by_frenzy = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 300,
		},
	},
	d_uniq_boss_frosterRoad_ice_age = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.9119487,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 200,
		},
	},
	deadparts_Force = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	elevatemagicsquare_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	first_grade_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 3.0726418,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	gesti_Slow = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 800,
		},
	},
	gesti_spread1 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 60.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	gesti_spread2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 140.0,
			length = 100.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	gesti_spread3 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 180.0,
			length = 140.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	gm_stake_stockades_knokdown = {
		{
			timestart = 0,
			timeend = 0,
			angle = -2.4849007,
			width = 10.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	gpad_gr_katyn_1_s7_1 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.4962163,
			width = 100.0,
			length = 600.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 2000,
		},
	},
	gpad_gr_katyn_1_s7_2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.41876349,
			width = 100.0,
			length = 300.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 2000,
		},
	},
	gpad_gr_katyn_1_s7_3 = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.41876349,
			width = 100.0,
			length = 100.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 100,
		},
	},
	gravity_floor = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 120.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	gtower_killthemall = {
		{
			timestart = 0,
			timeend = 0,
			angle = -1.1771666,
			width = 500.0,
			length = 50.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 1000,
		},
	},
	gtower_mon_darkground = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0025850763,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	gtower_push_dir5 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 500.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	gtower_together_strong = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.2995154e-15,
			width = 80.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	helgasercle_atk = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 70.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	helgasercle_atk2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 700,
		},
	},
	helgasercle_atk3 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0025850763,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	indunTheEnd = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 30.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	kubas_prominence = {
		{
		},
	},
	lachrymator_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	lecifer_spread1 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 60.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	lecifer_spread2 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 140.0,
			length = 100.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	lecifer_spread3 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 180.0,
			length = 140.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 4,
			updateterm = 0,
		},
	},
	merregina_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	merregina_pad_pc_summon = {
		{
			timestart = 0,
			timeend = 0,
			angle = -0.0075271176,
			width = 45.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	mineloader_laser = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 25.0,
			length = 38.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	molich_magicfinish = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 400,
		},
	},
	plant_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 75.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	plant_pad_born = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 0.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	plantattack = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 75.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 350,
		},
	},
	pollution_zone = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 150.0,
			length = 60.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	prominence = {
		{
		},
	},
	punji_stake = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 25.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	rootopus_line = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 120.0,
			length = 10.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 200,
		},
	},
	rope_pad = {
		{
		},
	},
	sapperPillarCheck_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	servantpad_DARKATK = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	servantpad_MDEF = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	servantpad_SP = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	servantpad_SR = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	servantpad_STA = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 100.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	shootpad_Denoptic = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	shootpad_Mothstem = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 23.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	shootpad_Neop = {
		{
			timestart = 0,
			timeend = 0,
			angle = 1.0,
			width = 15.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	shootpad_Sparnanman = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 20.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	shootpad_Unknocker = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	shootpad_lepus = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 6.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	shootpad_spector = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	stereatrofh_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 50.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	uniq_id_boss_Tantaliser_square = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 40.0,
			length = 100.0,
			typ = "Square",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 1,
			updateterm = 0,
		},
	},
	varleking_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 200.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	velcofer_curse_pad = {
		{
			timestart = 0,
			timeend = 0,
			angle = 2.272738,
			width = 70.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
	ykTest1 = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 5.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 100,
		},
	},
	zombie_wall = {
		{
			timestart = 0,
			timeend = 0,
			angle = 0.0,
			width = 10.0,
			length = 0.0,
			typ = "Circle",
			rotate = 0,
			mode = "PadSkill",
			checkertype = 0,
			updateterm = 0,
		},
	},
}
PSEUDOFORECASTPADSKILL_rawdata=data