

function BARRACK_CHARLIST_ON_INIT_PRELOADER(addon,frame)
    BARRACK_CHARLIST_ON_INIT_OLD(addon,frame)
    PRELOADER_PRELOAD_BARRACK_PRE(addon,frame)
end
if BARRACK_CHARLIST_ON_INIT~=BARRACK_CHARLIST_ON_INIT_PRELOADER then
    BARRACK_CHARLIST_ON_INIT_OLD=BARRACK_CHARLIST_ON_INIT
    BARRACK_CHARLIST_ON_INIT=BARRACK_CHARLIST_ON_INIT_PRELOADER
end
